im-practices/.github

workflow-templates/im-build-cleanup-releases-for-branches.properties.json
workflow-templates/im-build-cleanup-releases-for-branches.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-increment-version-on-merge.yml

- Modify the CI workflow to run for closed pull_requests, specifically merges to main
- When a merge to main happens run the branch release cleanup action.
- Adding a standalone workflow for cleaning up branch releases
- Add a note to the increment-version-on-merge workflow that it's not appropriate to run for repos that update the version in their CI builds

ARCH-1017/ARCH-1016 merging to main 

---

workflow-templates/im-build-dotnet-ci.yml

- Reduce the number of redundant builds: no need for dotnet test and dotnet publish to rebuild
- Include the calculated version number in the published assemblies
- Add an alternative step for zipping a published release on a Windows runner.
- Don't fail the finish-build job if "Send Status to Teams" or "Comment on PR" fails.
- Updated github-script to v5
- various whitespace and quoting cleanups

Various small improvements to im-build-dotnet-ci

---

workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-run-tf-destroy.yml
workflow-templates/im-run-tf-import.yml
workflow-templates/im-run-tf-taint.yml
workflow-templates/im-run-unlock-tf-state.yml
workflow-templates/im-run-validate-deployed-terraform.yml

Removing central logging ssh key from each of the workflows since it is now deprecated.

ARCH-1146 - Remove central logging

---

workflow-templates/im-build-nuget-package.yml

`REPO_URL` and `ORGANIZATION` can come directly from github context instead of being set by hand.
Moving the version determination earlier and packaging the NuGet at the same time as build to speed things up just a little and ensure the build properties, and especially the version numbers of the assembly and package align with each other.
Removing the redundant build triggered by the call to `dotnet test`

Simplified the build-nuget-package template

---

workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-az-swap-app-slots.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-multiple-items-at-once.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-on-prem-website.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-annotate-app-insights.yml
workflow-templates/im-run-delete-azure-blob.yml
workflow-templates/im-run-flyway-repair.yml
workflow-templates/im-run-start-stop-restart-azure-app.yml
workflow-templates/im-run-tf-destroy.yml
workflow-templates/im-run-tf-import.yml
workflow-templates/im-run-tf-taint.yml
workflow-templates/im-run-unlock-tf-state.yml

Update any usages of `env.ENVIRONMENT` to `github.event.inputs.environment` when used to populate `environment:`.  
The env context is not available to jobs.id.environment. You can only use things from the github, needs, strategy, matrix or inputs contexts in that field. Which makes sense because before we would have been using an output from the set-vars job (the needs context). Using the env.ENVIRONMENT variable in other places where just fine where it had access to the env context so there was no naming clash which is initially what I thought might be happening.

ARCH-1190 - Update any usages of `env.ENVIRONMENT` in `environment:`

---

workflow-templates/im-test-sam-yaml.yml

Because the stewardship export is on by default, this must run on a self-hosted runner, otherwise the json upload will come from the public internet and will be blocked by Cosmos IP restrictions.

Updating im-test-sam-yaml to use self-hosted runners.

---

workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-windows-service.yml

Update iis site and windows service workflows for multiple machine deploys
The deploy jobs are what will be run multiple times via a matrix.  I was hoping to cut down as much as possible on the repetitive jobs like the octostache/variable substitution but I think that's just going to have to be run multiple times.  
We could potentially cut out the duplication if the deploy job did all the setup for octostache/variable substitution etc and then called the reusable workflow multiple times but you would have to [pass in all of the environment variables](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations) that you set up for the action (which can be significant).  
>Any environment variables set in an env context defined at the workflow level in the caller …

ARCH-1601 - Multi-machine deploys

---

workflow-templates/im-build-nuget-package.yml

Tweak nuget workflow to use NEXT_VERSION_NO_PREFIX instead of manipulating the NEXT_VERSION string

Use NEXT_VERSION_NO_PREFIX arg in nuget workflow

---

workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-run-flyway-repair.yml

The run-flyway-command action now allows for using an azure service principal or managed service identity to authenticate with the database. We're updating the action's version and adding some instructions around that.

Update the run flyway command and add new instructions.

---

.github/workflows/reusable-examine-triggers.yml
.github/workflows/reusable-validate-tag.yml

Reusable workflow that can be used as a job in various team workflows.
Note that it is a requirement that they reside within the `.github/workflows` directory.
Note one problem with placing them in `.github` repo is they will need to include tagged versions so they can be referenced by other repos.
Another example is having these reusable workflows live more closely to what they are using.
https://github.com/im-open/is-release-production-ready/pull/8

Add reusable workflows

---

README.md
workflow-templates/im-build-db-ci.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-az-swap-app-slots.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-multiple-items-at-once.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-annotate-app-insights.yml
workflow-templates/im-run-delete-azure-blob.yml
workflow-templates/im-run-flyway-repair.yml
workflow-templates/im-run-start-stop-restart-azure-app.yml
workflow-templates/im-run-tf-destroy.yml
workflow-templates/im-run-tf-import.yml
workflow-templates/im-run-tf-taint.yml
workflow-templates/im-run-unlock-tf-state.yml
workflow-templates/im-run-validate-deployed-terraform.yml
workflow-templates/im-test-k6-ci.yml
workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator.yml
workflow-templates/im-test-postman.yml

- Switch instances of `[self-hosted, ubuntu-20.04]` to `[self-hosted, im-linux]`
- In db ci and dotnet ci workflows, setup the services for the jobs that use the sql server.  The im-linux runners do not contain this by default.

ARCH-1853 - Switching to im-linux runners

---

.github/workflows/im-reusable-finish-build-workflow.yml
.github/workflows/im-reusable-finish-deployment-workflow.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-npm-package.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-az-swap-app-slots.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-annotate-app-insights.yml
workflow-templates/im-run-start-stop-restart-azure-app.yml
workflow-templates/im-run-tf-destroy.yml
workflow-templates/im-run-tf-import.yml
workflow-templates/im-run-tf-taint.yml
workflow-templates/im-run-unlock-tf-state.yml
workflow-templates/im-run-validate-deployed-terraform.yml
workflow-templates/im-test-cypress.yml
workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator.yml

Update templates to use vars context where appropriate instead of secrets.  This applies to:
- DEPLOY_NOTIFICATIONS_CHANNEL
- MS_TEAMS_URI
- PAGERDUTY_SERVICE_ID
- ARM_TENANT_ID
- ARM_CLIENT_ID
- ARM_SUBSCRIPTION_ID

ARCH-1856 - Transition to vars context from secrets context

---

workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-run-tf-destroy.yml

Remove the unnecessary legacy auth protocol and additional request when downloading or uploading terraform plan output.
The `Storage Blob Data Owner` role has ben added to each BC resource group SP.
https://github.com/im-platform/development/pull/1000

Remove the legacy auth protocal

---

.github/workflows/im-reusable-setup-deployment-workflow.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-tf-destroy.yml

The runs-on is defined inside the job, so it shouldn't be included in the caller workflow.

Remove the runs-on keyword from reusable workflow jobs.

---

workflow-templates/im-build-db-ci.yml

Updating workflows to comply with GitHub's request to deprecate the `set-output` & `save-state` command in workflows/actions.

ARCH-1907 - Remove instances of set-output

---

workflow-templates/im-test-k6-operator-approval.yml

*  Fixing kubctl login when workflow cancelled

SRE-297 - Fixing kubctl login when workflow cancelled

---

workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

- The official actions/cache action now supports a lookup-only arg.  Replace the check-for-cache with actions/cache.  
- Take the opportunity to make it cross-platform as well.
- Change the conditions.  The actions/cache action only has an output if the cache-hit is true.  If the cache-hit is false there are no outputs.  This is weird in my opinion but it means the condition needs to change.

ARCH-1919 - Updating cache check action

---

workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-nuget-package.yml

In order to make it easier for teams to zip before uploading a composite action was created in im-open called [zip-upload-artifact](https://github.com/im-open/zip-upload-artifact). It takes the same inputs as [upload-artifact](https://github.com/actions/upload-artifact) so making the switch is as easy as changing the `uses` string.
For usage examples see workflows in:
- [account-management](https://github.com/im-enrollment/account-management/pull/1513)
- [agent-management](https://github.com/im-customer-engagement/agent-management/pull/1745)
- [frontend-tooling-bff](https://github.com/im-enrollment/frontend-tooling-bff/pull/803)
- [github-governance](https://github.com/im-platform/github-governance/blob/main/.github/workflows/github-code-search.yml#L48)
- …

PLPT-564 Use zip-upload-artifact composite action instead of upload-artifact

---

workflow-templates/im-build-dotnet-ci.yml

Fixing inputs for the finish-build job.  The NEXT version is not generated by the deployment artifacts job anymore, it comes from the setup build job.

Fix finish-build inputs

---

.github/workflows/im-reusable-finish-build-workflow.yml
.github/workflows/im-reusable-finish-deployment-workflow.yml
.github/workflows/im-reusable-setup-build-workflow.yml
.github/workflows/im-reusable-setup-deployment-workflow.yml

* Adding runs-on input - thus allowing teams to pick the runner and decreases load in the im-linux runner.
* Added deploy label for custom labels with updated deployment board action

WE-19955 - Adding runs-on and deploy-label

---

.github/workflows/im-reusable-finish-deployment-workflow.yml

*  Enable deployment slot tracking with deployment board
* Depends on pull request https://github.com/im-open/update-deployment-board/pull/36

EN-20312 - Enable deployment slot tracking with deployment board

---

workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml

GitHub actions runners don't have the ability to pre-load PowerShell modules used int Azure SQL access and role assignments.  This adds the module installation to the template workflows.

Updates for GH actions runner changes

---

workflow-templates/im-build-db-ci.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-run-tf-destroy.yml

There was an issue in 1up-infrastructure when it tried to download a blob because the plan name output it was using was empty. 
In the plan job, the plan blob name was being set in pwsh with an echo statement.  When I changed that echo statement to the pwsh syntax the plan name output was populated and the apply job was able to download the plan blob.
There wasn't an issue using the echo statements with pwsh to set outputs before but GitHub may have made a change (or maybe our self-hosted runners changed) so that it no longer works.
```sh
echo "tf_plan_name=$terraformPlanName" >> $GITHUB_OUTPUT # No longer works
"tf_plan_name=$terraformPlanName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append # This syntax works
```

ARCH-2007 - Update the way outputs are set in pwsh

---

start-project-template-inventory.json

We'll no longer be using the update-deployment-board and cleanup-deployment-board actions and won't need the dedicated clean up deployment board workflow

Remove Cleanup Deployment Board

---

workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-test-cypress.yml
workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

The Purple Team has created [PLPT-697](https://jira.extendhealth.com/browse/PLPT-697) to update workflows that upload artifacts using v4.
Replacements Made:
- Changed usages of `zip-upload-artifact` to use `upload-artifact@v4`
- Updates usages of `upload-artifact` to use `v4`

Use Upload-Artifact v4

---

.github/workflows/im-reusable-finish-build-workflow.yml
.github/workflows/im-reusable-finish-deployment-workflow.yml
.github/workflows/im-reusable-setup-build-workflow.yml
.github/workflows/im-reusable-setup-deployment-workflow.yml
.github/workflows/increment-version-and-kick-off-sync.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-npm-package.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-tf-destroy.yml

- Update actions versions to use the node20 version
- Add an input for ms-teams-uri & deploy-notifications-channel for the finish reusable workflows.  These are mainly defined as variables now but we're still treating them as secrets.  Allow caller to provide it either way. +semver:minor
- Adding a step to each reusable workflow to print out the value of each input to make it easier to see what the workflow will be using
- Add update-deployment-board permissions to the deployment workflows with a TODO to remove once we are ready to switch to techhub deploys (this affected at least one team)

ARCH-2011 - Updating for node20 versions & other updates

---

.github/workflows/im-reusable-finish-deployment-workflow.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-tf-destroy.yml

Adding a way to skip the update-deployment-board step in the im-reusable-finish-deployment-workflow without creating a breaking change yet.  There are around 70 usages of this reusable workflow and about half of those rely on the default value being 1 for the `deployment-board-number` input which is why it's a little hacky with the -1.  If we prefer a different input like `skip-deployment-board-update` could be temporarily introduced and then removed with the rest of the update-deployment-board functionality.  I don't think this will be very long-lived whichever way we go.
I added a second step that spells out why the first step might be skipped just for a little bit of additional info that can clue users into the fact that skipping is now an option.  That step can be removed once we make …

WIP - ARCH-2065 - Skip update-deployment-board step

---

.github/workflows/im-reusable-finish-build-workflow.yml
.github/workflows/im-reusable-finish-deployment-workflow.yml
.github/workflows/im-reusable-setup-build-workflow.yml
.github/workflows/im-reusable-setup-deployment-workflow.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-npm-package.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-multiple-items-at-once.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-tf-destroy.yml
workflow-templates/im-run-validate-deployed-terraform.yml

- Remove deprecated inputs from the reusable finish deployment workflow
- Make techhub deployment related inputs required in the finish deployment workflow
- Update workflow templates to use latest reusable workflow versions (@v3) & modify inputs accordingly
- Update permissions in each of the "deploy" templates now that deployment-board permissions are no longer needed

ARCH-2088 - +semver:breaking Changes for TechHub deployments

---

workflow-templates/im-test-k6-ci.yml
workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

* Changed variable for k6 ci and k6 manual workflows to use Actions variable
* Adding influxdb push interval to workflows

SRE-610 - K6 Workflow Updates

---

.github/workflows/im-reusable-validate-catalog-info.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-test-catalog-info.properties.json
workflow-templates/im-test-catalog-info.yml

The PR creates a new reusable workflow for validating catalog-info.yml files.  It has been incorporated into the workflow templates in two ways: as part of the CI build or as a standalone validation workflow.
To see it in action:
- [File changed and `only-validate-if-file-changed=true`](https://github.com/im-practices/1UP/actions/runs/9980832184/job/27583127036#step:5:42)
- [File did not change and `only-validate-if-file-changed=true`](https://github.com/im-practices/1UP/actions/runs/9980946516/job/27583481442#step:5:42)
- [File did not change but `only-validate-if-file-changed=false`](https://github.com/im-practices/1UP/actions/runs/9980956679/job/27583514148#step:5:42)
- [File changed and `only-validate-if-file-changed=true`](https://github.com/im-practices/1UP/actions/runs/9980831829/jo …

ARCH-2122 - Adding reusable workflow for validating catalog-info.yml

---

.github/workflows/im-reusable-finish-build-workflow.yml
.github/workflows/im-reusable-finish-deployment-workflow.yml
.github/workflows/im-reusable-setup-build-workflow.yml

* Adding Teams Notification custom-action as an input
* Adding version in Annotation for build reusable workflow.

EN-23320 - Adding Teams action in reusable workflows

---

workflow-templates/im-deploy-techdocs-site.yml

- Implement the two most common triggers
- Add some additional checking around the docs that will be published to each container
- Use the push trigger over pull_request so we don't have to also do a check for `merged`
- Add workflow summary & more specific `run-name`

ARCH-2142 - Update TechDocs Publishing

---

.github/workflows/im-reusable-finish-deployment-workflow.yml

Fix for the teams check. The `if` did not like the same syntax as the input or the js code above because `if` does not have access to the `secrets` context.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#context-availability

Teams Check Fix

---

.github/workflows/im-reusable-setup-build-workflow.yml

- Added outputs `NEXT_RELEASE_VERSION` and `NEXT_RELEASE_VERSION_NO_PREFIX`.  
- Updating to latest git-version-lite action

SRE-208 - Updating workflow to output NEXT_RELEASE_VERSION.

---

.github/workflows/im-reusable-finish-deployment-workflow.yml

* Added input deployment-description to finish-workflows.

SRE-665 - Adding deployment description

---

workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

* Missed updating powerstate code in another job
* Fixed needs section with approval job being renamed.

SRE-671 - Fixing k6-operator workflow errors

---

workflow-templates/im-run-aks-scale-cluster.yml

* After further testing, found scheduled workflow run didn't handle a schedule scenario.  Fixed to handle the special case.
* Included restarting of pods in a failed state after scale up.  This is due to scaling not allowed during scale down and pods can't find resources.

SRE-657 - Adding improvements for aks scale cluster workflow

---

workflow-templates/im-run-aks-scale-cluster.yml

* Making Restart Pods step more reliable and put in longer waits
* added more options to set autoscale after scaling down.

SRE-671 - AKS Scaling workflow update

---

workflow-templates/im-build-dotnet-ci.yml

Replacing `im-open/restore-cache@v1.3` with `actions/cache/restore@v4` because :
- The official cache action now includes a restore action: https://github.com/actions/cache/blob/main/restore/README.md
- The GitHub cache API on which  `im-open/restore-cache@v1.3` depends [has been deprecated](https://github.com/actions/cache/discussions/1510)

replacing im-open/restore-cache@v1.3 with actions/cache/restore@v4
