workflow-templates/im-deploy-cleanup-automated-board.properties.json
workflow-templates/im-deploy-cleanup-automated-board.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manually-apply-to-dev-subscription.yml
workflow-templates/im-deploy-tf-manually-apply-to-prod-subscription.yml

Including a template for cleaning issues on an automated deployment board and template updates to update the automated deployment board.

ARCH-867 - Automated Deployment Board

---

workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-az-app-service-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-app-service-manually-to-prod-subn.yml
workflow-templates/im-deploy-az-swap-slots.properties.json
workflow-templates/im-deploy-az-swap-slots.yml
workflow-templates/im-deploy-cleanup-automated-board.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manually-apply-to-dev-subscription.yml
workflow-templates/im-deploy-tf-manually-apply-to-prod-subscription.yml
workflow-templates/im-test-checkmarx-cli-sast-scan.yml

- Restrict the tf auto plan & comment & tf auto apply to dev on merge to when changes have been made to the tf files
- Fix the PAGERDUTY_SERVICE_IDS env var, it needs quotes around the secret
- Update add-or-update-json-properties action to v1.0.1 where there was a bug fix
- Introducing slot steps and a teams notification in the deploy az app service to dev/prod subscription.
- Update the checkmarx workflow so it only kicks off when there are changes to the src directory

ARCH-889 - Adding slot swapping & other template updates

---

workflow-templates/im-run-add-or-update-az-keyvault-secret.properties.json
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml

If you want to see it in action:
https://github.com/bc-swat/1UP/actions/runs/1072825727

ARCH-888 - Adding a template for adding an az keyvault secret.

---

workflow-templates/im-run-start-stop-restart-azure-app-service.properties.json
workflow-templates/im-run-start-stop-restart-azure-app-service.yml
workflow-templates/im-run-start-stop-restart-azure-function-app.properties.json
workflow-templates/im-run-start-stop-restart-azure-function-app.yml

Adding a workflow templates for starting/stopping/restarting azure app service and function apps.
If you want to see it in action:
https://github.com/bc-swat/1UP/actions/workflows/im-run-start-stop-restart-azure-app-service.yml

ARCH-887 - starting/stopping/restarting apps

---

workflow-templates/im-deploy-az-app-service-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-app-service-manually-to-prod-subn.yml
workflow-templates/im-deploy-az-function-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-function-manually-to-prod-subn.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-annotate-app-insights.properties.json
workflow-templates/im-run-annotate-app-insights.yml
workflow-templates/im-run-start-stop-restart-azure-app-service.yml
workflow-templates/im-run-start-stop-restart-azure-function-app.yml

- Updating workflow templates to use the app insights annotation.
- Adding a new workflow for annotating.
- Also adding a logout to the other runbook workflow templates.
If you'd like to see it in action:
On the workflow:
https://github.com/bc-swat/1UP/actions/workflows/im-run-annotate-app-insights.yml
On App Insights:
https://portal.azure.com/#@twonline.onmicrosoft.com/resource/subscriptions/78dd0cb9-70cd-4cd5-8d3d-414581e421c9/resourceGroups/BDAIM-D-NA26-level-up-RGRP/providers/Microsoft.Insights/components/level-up-dev-APPINSIGHTS/performance

ARCH-890 - App Insights Annotations

---

workflow-templates/im-test-cypress.properties.json
workflow-templates/im-test-cypress.yml
workflow-templates/im-test-storyteller.yml

This workflow was copied into [bc-swat/apps-policies-micro-frontend](https://github.com/bc-swat/apps-policies-micro-frontend/actions/runs/1083137998) if you want to see it in action.

ARCH-882 - Workflow template for cypress tests

---

workflow-templates/im-test-postman.properties.json
workflow-templates/im-test-postman.yml

If you want to see it in action:
Workflow status check: https://github.com/bc-swat/participant-guidance/runs/3224523071?check_suite_focus=true
PR Comment: https://github.com/bc-swat/participant-guidance/pull/1

ARCH-884 - Adding a workflow template for postman tests

---

workflow-templates/im-build-db-ci.properties.json
workflow-templates/im-build-db-ci.yml

This is my first attempt at creating one of these templates, so please judge it as harshly as possible! It's also a bit of a weird one because a lot of repos will only need half or less of what's in here.

ARCH-745: Adding the build database ci workflow template

---

workflow-templates/im-build-db-ci.yml
workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-az-app-service-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-app-service-manually-to-prod-subn.yml
workflow-templates/im-deploy-az-function-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-function-manually-to-prod-subn.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manually-apply-to-dev-subscription.yml
workflow-templates/im-deploy-tf-manually-apply-to-prod-subscription.properties.json
workflow-templates/im-deploy-tf-manually-apply-to-prod-subscription.yml
workflow-templates/im-test-storyteller.yml

- Adding deployment board link to any workflow using it
- Switch on-prem-egress-ip to network-information for ssh keys
- In tf deploys move setting of RESOURCE_GROUP and STORAGE_ACCOUNT from hardcoded values to ones set by an action
- In az func deploys move AZURE_FUNC_NAME from hardcoded value to one set by an action
- In az app service deploys move AZURE_APP_NAME from hardcoded value to one set by an action
- In az app/func deploys move AZURE_INSIGHTS_NAME from hardcoded value to one set by an action
- In storyteller and database ci workflows change runner from windows-2019-dev to windows-2019

ARCH-815 - Addressing some items we found when working with data practices

---

.github/workflows/increment-version-and-kick-off-sync.yml
workflow-templates/im-build-context-dump-workflow.yml
workflow-templates/im-build-db-ci.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-increment-version-on-merge.yml
workflow-templates/im-deploy-az-app-service-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-app-service-manually-to-prod-subn.yml
workflow-templates/im-deploy-az-function-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-function-manually-to-prod-subn.yml
workflow-templates/im-deploy-az-swap-app-service-slots.yml
workflow-templates/im-deploy-az-swap-function-slots.yml
workflow-templates/im-deploy-tf-manually-apply-to-dev-subscription.yml
workflow-templates/im-deploy-tf-manually-apply-to-prod-subscription.yml

Remove [] if there is only one label for the runs-on prop.

ARCH-999 - Force using github-hosted runners 

---

workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manually-apply-to-dev-subscription.yml
workflow-templates/im-deploy-tf-manually-apply-to-prod-subscription.yml

- Update tf version to 1.0.5
- Add on-prem-egress-ips ssh key (storage account network rules uses it)
- Rename the deploy workflows so they show up more usefully
- Replace github.event.inputs.environment with the cleaned input (needs.validate-input.outputs.env) anywhere it was used
- rename the technical-approval step to clarify what it is for

Template updates

---

workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-deploy-az-app-service-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-app-service-manually-to-prod-subn.yml
workflow-templates/im-deploy-az-function-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-function-manually-to-prod-subn.yml
workflow-templates/im-deploy-npm-package.yml
workflow-templates/im-deploy-nuget-package.yml
workflow-templates/im-test-cypress.yml
workflow-templates/im-test-postman.yml
workflow-templates/im-test-storyteller.yml

Adding the orgs argument with TODO to the authenticate-with-github-package-registries action.  Add a comment to the action indicating you may need to delete a local project nuget.config.

ARCH-999 - authenticate-with-github-package-registries update

---

.github/workflows/increment-version-and-kick-off-sync.yml
workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-az-app-service-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-app-service-manually-to-prod-subn.yml
workflow-templates/im-deploy-az-function-manually-to-dev-subn.yml
workflow-templates/im-deploy-az-function-manually-to-prod-subn.yml
workflow-templates/im-deploy-az-swap-app-service-slots.yml
workflow-templates/im-deploy-az-swap-function-slots.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manually-apply-to-dev-subscription.yml
workflow-templates/im-deploy-tf-manually-apply-to-prod-subscription.yml
workflow-templates/im-test-checkmarx-cli-sast-scan.yml

Making a note about which items are org level secrets.  Change secrets.PAGERDUTY_TOKEN => secrets.PAGERDUTY_API_KEY.

ARCH-999 - Org level secrets

---

.github/workflows/increment-version-and-kick-off-sync.yml
README.md
workflow-templates/im-build-context-dump-workflow.yml
workflow-templates/im-build-db-ci.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-increment-version-on-merge.yml
workflow-templates/im-deploy-az-app-service-manually.yml
workflow-templates/im-deploy-az-function-manually.yml
workflow-templates/im-deploy-az-swap-app-service-slots.yml
workflow-templates/im-deploy-az-swap-function-slots.yml
workflow-templates/im-deploy-cleanup-automated-board.yml
workflow-templates/im-deploy-tf-manual-apply.yml

Switching from ubuntu-18.04 to ubuntu-latest.  Making a couple of changes on the cleanup deployment board workflow.

ubuntu-latest

---

README.md
workflow-templates/im-deploy-az-app-service-manually.yml
workflow-templates/im-deploy-az-function-manually.yml
workflow-templates/im-deploy-az-swap-app-service-slots.yml
workflow-templates/im-deploy-az-swap-function-slots.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-annotate-app-insights.yml
workflow-templates/im-run-start-stop-restart-azure-app-service.yml
workflow-templates/im-run-start-stop-restart-azure-function-app.yml
workflow-templates/im-test-k6-manual.yml

- Implement the set-vars job pattern in the workflows that take in an environment.  
- Have each job print out which environment is being targeted as the first step.

ARCH-1010- set-vars job pattern

---

.github/workflows/increment-version-and-kick-off-sync.yml
workflow-templates/im-build-increment-version-on-merge.yml
workflow-templates/im-deploy-az-app-service-manually.yml
workflow-templates/im-deploy-az-function-manually.yml

Also fix the octostache template usage.

ARCH-1018 - Replace increment logic with the git-version-lite action.

---

workflow-templates/im-run-validate-deployed-terraform.properties.json
workflow-templates/im-run-validate-deployed-terraform.yml

If you want to see this template in action: https://github.com/bc-swat/1UP-infrastructure/actions/runs/1222855697

ARCH-879 - Adding a worflow for infrastructure validation.

---

workflow-templates/im-build-increment-version-on-merge.yml
workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-run-validate-deployed-terraform.yml
workflow-templates/im-test-checkmarx-cli-sast-scan.yml

I did not increment the version on the two repos that had comment only changes

ARCH-1043 - Adding some template fixes after the first migration

---

workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-run-validate-deployed-terraform.properties.json
workflow-templates/im-run-validate-deployed-terraform.yml

Adjusting the terraform plan/applys to use a lock or a lock timeout.  Switch the auto apply to use a matrix in case teams want to run this for more than one environment.

ARCH-1043 - tf-locks

---

workflow-templates/im-build-db-ci.yml
workflow-templates/im-build-dotnet-ci.yml

The most important changes are the version number updates on some of the actions, but I took the opportunity to make other general improvements too.

Various improvements to the build db workflow template

---

workflow-templates/im-deploy-on-prem-website.yml
workflow-templates/im-deploy-windows-service.json
workflow-templates/im-deploy-windows-service.yml

- Updated on-prem website with windows deploy file action
- Finished windows service deployment workflow

ARCH-878: Deploy On Prem Windows Service

---

workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-annotate-app-insights.yml
workflow-templates/im-run-flyway-repair.yml
workflow-templates/im-run-start-stop-restart-azure-app.yml

Ensure each login has a logout and that each login step has an id where it is referenced by logout

Logout Fixes 

---

README.md
workflow-templates/im-run-add-or-update-az-keyvault-secret.properties.json
workflow-templates/im-run-annotate-app-insights.properties.json
workflow-templates/im-run-start-stop-restart-azure-app.properties.json
workflow-templates/im-run-tf-import.properties.json
workflow-templates/im-run-tf-taint.properties.json
workflow-templates/im-run-tf-taint.yml
workflow-templates/im-run-unlock-tf-state.yml

- Update the svg that some of the other runbooks use
- Remove an used arg from some of the tf runbooks

ARCH-985 - Create tf taint workflow.

---

workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-on-prem-website.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-test-k6-manual.yml

- Modify deployment workflows to post to the deployment notifications room
- Adding some context to the k6 workflow and fix the environment input
- Removing the event from the post-status-to-teams actions since the action includes that by default

ARCH-1049 - Post Prod Deployments

---

workflow-templates/im-deploy-az-app-manually.yml

Added `chmod` statement to allow the workflow user to update/edit files for configuration from the package zip.

Bug fix: unzip files account access

---

workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-az-swap-app-slots.yml
workflow-templates/im-deploy-on-prem-website.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-annotate-app-insights.yml
workflow-templates/im-run-start-stop-restart-azure-app.yml

- Added a link to the usage information for set-variables-by-scope action﻿

ARCH-1117: Set Vars Usage Link

---

workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-on-prem-website.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-service.yml

I wanted to add a note about the Jira org secrets to the comments about the Jira transition action to forestall the inevitable questions we'd likely get.

Add a note about Jira secrets

---

workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-on-prem-website.yml
workflow-templates/im-deploy-windows-service.yml

Updated the workflows that use the Octostache action to use the new .net 6.0 framework version.

ARCH-1203: Updated to the latest ocotstache action

---

workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-run-flyway-repair.yml

* Making the repair workflow handle on-prem databases.
* Small improvements to the on-prem deploy workflow.

Updating on-prem database workflows

---

workflow-templates/im-test-k6-ci.yml
workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator.yml

* Added comment of influxdb addresses for each subscription.
* Updated manual k6 workflow to point to prod influxdb.

SRE-230 - Updated influxdb address

---

workflow-templates/im-test-k6-ci.yml
workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator.yml

* Removed hard coded value and used input
* Checkout gitub.ref_name so you can checkout a branch from the github ui.

SRE-230 - Fixed bug in k6-operator workflow

---

workflow-templates/im-test-k6-manual.yml

Updated default paramaters to avoid error.

SRE-231 - Updated default paramaters to avoid error. 

---

workflow-templates/im-test-k6-ci.yml
workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator.yml

* Added K6 subfolders support
* Added support for K6 extensions

SRE-233 - K6 Support Subfolders and k6 extension support

---

workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator.yml

* Change working directory input to an environment variable.

SRE-233 - Change Working Directory to Env Variable

---

workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator.yml

* Removed deprecated comments
* Added teams notification to manual workflow.

SRE-233 - K6 Template - Removed deprecated comments

---

workflow-templates/im-test-k6-operator.yml

* Fixed extra space
* Added new inputs for the k6-operator action
* https://jira.extendhealth.com/browse/SRE-235

WE-16978 - k6 operator bugfix

---

workflow-templates/im-test-k6-operator.yml

* Updated K6 Operator workflow to work with latest k6-operator action.

K6 Operator - Typo of parameter

---

workflow-templates/im-test-k6-operator.yml

* Added check if cluster is running

WE-17588 - K6-Operator: Added check if cluster is running. 

---

workflow-templates/im-test-k6-ci.yml
workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator.yml

* Updated to latest actions and annotation improvements.

SRE-241 - K6 Operator workflow updates

---

workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml

Updating templates so they point at the im-open version of variable-substitution.

ARCH-1832 - Updating variable-substitution action

---

workflow-templates/im-test-k6-operator.yml

* Updated login method of kubectl to use azure cli.

SRE-250 - K6 Operator - Updating login of kubectl

---

.github/workflows/im-reusable-finish-build-workflow.yml
.github/workflows/im-reusable-finish-deployment-workflow.yml
.github/workflows/im-reusable-setup-build-workflow.yml
.github/workflows/im-reusable-setup-deployment-workflow.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-npm-package.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-multiple-items-at-once.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-tf-destroy.yml

This PR defines and implements the setup-build-workflow.  Tested in 1up: https://github.com/im-practices/1UP/actions/runs/4962651744

ARCH-1831 - Initial commit for setup build workflow

---

workflow-templates/im-test-k6-operator.yml

SRE-250 - K6 Operator  workflow to add back influxdb output

---

workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-multiple-items-at-once.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-tf-destroy.yml

- Include the workflows folder in the reference that were missing it.

Reusable workflow fix

---

workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-az-swap-app-slots.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-techdocs-site.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-annotate-app-insights.yml
workflow-templates/im-run-delete-azure-blob.yml
workflow-templates/im-run-flyway-repair.yml
workflow-templates/im-run-start-stop-restart-azure-app.yml
workflow-templates/im-run-tf-destroy.yml
workflow-templates/im-run-tf-import.yml
workflow-templates/im-run-tf-taint.yml
workflow-templates/im-run-unlock-tf-state.yml
workflow-templates/im-run-validate-deployed-terraform.yml
workflow-templates/im-test-k6-operator.yml

- Updating workflow templates to use secretless deployments and az cli calls

ARCH-1872 - Secretless access & deploys

---

workflow-templates/im-test-k6-operator.yml

* This will not require the runner to have kubectl and kubelogin

SRE-259 - Adding kubectl and kubelogin install steps

---

workflow-templates/im-test-k6-operator.yml

* updated runner for npm step.

SRE-259 - Updated to default im-linux runner.

---

.github/workflows/im-reusable-setup-build-workflow.yml
workflow-templates/im-build-nuget-package.yml

- Fix output value for is merge to main in setup build workflow
- Fix referenced IS_PRERELEASE output in build nuget package workflow

Reusable workflow fixes

---

workflow-templates/im-test-k6-operator-approval.properties.json
workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

* Added K6Operator workflow with approvals to handle long running test timeouts

SRE-260 - Added K6Operator workflow with approvals

---

workflow-templates/im-build-tf-auto-plan-and-comment-on-prs.yml
workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-techdocs-site.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-run-tf-destroy.yml
workflow-templates/im-run-tf-import.yml
workflow-templates/im-run-tf-taint.yml
workflow-templates/im-run-unlock-tf-state.yml
workflow-templates/im-run-validate-deployed-terraform.yml

- Remove extraneous az logins/logouts (not needed unless using az cli)
- Update terraform version
- Remove ARM_USE_OIDC and rely on it being set in terraform

ARCH-1873 - Update templates for secret-less deploys

---

workflow-templates/im-test-k6-ci.yml
workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

* Updated grafana url to filter dashboard
* Add env tag to default paramaters

SRE-267 - K6 Workflow update grafana and tags

---

workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

* Added PagerDuty Steps to workflows. 
* Found missing paramater for separate nodes in the workflow

SRE-297 - Updated workflows with pagerduty maintenance window

---

.github/workflows/im-reusable-setup-build-workflow.yml
workflow-templates/im-build-dotnet-ci.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-test-cypress.yml
workflow-templates/im-test-storyteller.yml

- In the setup build reusable workflow, create an output for the depe…
- Set explicit retention periods for all usages of upload-artifact
- Only upload code coverage reports if the actor is not dependabot

Save the Storage Space!

---

workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

* Moved `upload-type` input and made it an environment variable.
* Moved Cleanup if Cancelled steps to separate job.
* Added `maintenance-window-duration` as an input.
* Removing `run-name` input and deriving it from `test-file` input.

SRE-297 - K6 Operator Workflow Improvements

---

workflow-templates/im-build-db-ci.yml
workflow-templates/im-build-npm-package.yml
workflow-templates/im-build-nuget-package.yml
workflow-templates/im-test-cypress.yml
workflow-templates/im-test-postman.yml

Removing im-client.  None of the versions have been updated because it is only comments that were changed.

ARCH-2068 - Remove im-client from comments

---

workflow-templates/im-test-k6-manual.yml
workflow-templates/im-test-k6-operator-approval.yml
workflow-templates/im-test-k6-operator.yml

* Adding prometheus new ingest url and prometheus dashboard for managed prometheus to enable long term logs

SRE-610 - Adding prometheus new ingest url and prometheus dashboard

---

workflow-templates/im-deploy-az-app-manually.yml
workflow-templates/im-deploy-az-database.yml
workflow-templates/im-deploy-az-swap-app-slots.yml
workflow-templates/im-deploy-files-to-az-storage-account.yml
workflow-templates/im-deploy-iis-website.yml
workflow-templates/im-deploy-on-prem-database.yml
workflow-templates/im-deploy-tf-auto-apply-main-to-dev-on-merge.yml
workflow-templates/im-deploy-tf-manual-apply.yml
workflow-templates/im-deploy-windows-files.yml
workflow-templates/im-deploy-windows-service.yml
workflow-templates/im-run-add-or-update-az-keyvault-secret.yml
workflow-templates/im-run-delete-azure-blob.yml
workflow-templates/im-run-flyway-repair.yml
workflow-templates/im-run-start-stop-restart-azure-app.yml
workflow-templates/im-run-tf-destroy.yml
workflow-templates/im-run-tf-import.yml
workflow-templates/im-run-tf-taint.yml
workflow-templates/im-run-unlock-tf-state.yml

Adding annotate-app-insights and a pagerduty-change-events-action to relevant workflows.

ARCH-2140 - Adding annotate app insights & pd change events

---

.github/workflows/im-reusable-publish-techdocs.yml
workflow-templates/im-deploy-techdocs-site.yml

- Adding a new reusable workflow that publishes techdocs
- Update the techdocs workflow template to utilize the reusable workflow

ARCH-2142 - Reusable TechDocs

---

workflow-templates/im-test-playwright-manual.properties.json
workflow-templates/im-test-playwright-manual.yml
workflow-templates/im-test-playwright-schedule.properties.json
workflow-templates/im-test-playwright-schedule.yml

* Creating playwright workflow templates

SRE-208 - Creating playwright workflow templates

---

workflow-templates/im-test-playwright-schedule.yml

- Updating workflow to use matrix that can be outputed to both the annotation and strategy job.

SRE-208 - Playwright Schedule Workflow Update

---

workflow-templates/im-test-selenium-manual.properties.json
workflow-templates/im-test-selenium-manual.yml
workflow-templates/im-test-selenium-schedule.properties.json
workflow-templates/im-test-selenium-schedule.yml

- Create Selenium C# Scheduled workflow template
- Create Selenium C# Manual workflow template

QAP 503 Adding Selenium UI test manual and schedule workflows template
